- menu_name: "Links"

- name: "Privacy Policy"
  url: "/privacy/"
  title: "Privacy Policy"

- name: "Terms of Service"
  url: "/terms/"
  title: "Terms of Service"

# - name: "Contact"
#   url: "/contact/"
#   title: "Contact"

# - name: "RSS"
#   url: "/feed.xml"
#   title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"

# - name: "sitemap.xml"
#   url: "/sitemap.xml"
#   title: "Sitemap for Google Webmaster Tools"
